### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks, @JakobDev! :+1:

**Comment by travier** [comment]
https://discourse.flathub.org/t/freedesktop-sdk-22-08-0-released/2871/3

**Comment by RobLoach** [comment]
@travier Thanks for the heads up. Do you think we should revert this until the official announcement?

**Comment by travier** [comment]
I think you should, unless this fixes an issue that you were having before.

**Comment by JakobDev** [comment]
@RobLoach Just for curiosity: Why did RetroArch need the KDE Runtime? It has a custom GUI and did not use Qt at all.

**Comment by RobLoach** [comment]
There's a desktop UI that you can launch that uses Qt.

**Pull request merged**
