### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by RobLoach**
Hold on this until the 22.08 runtime is officially announced.

### CODE REVIEW

**Comment by tim77** [comment]
bot, build

**Comment by tim77** [comment]
New runtime released: https://discourse.flathub.org/t/freedesktop-sdk-22-08-0-released/2871.

But there minor issues and linter doesn't like:
```
    "errors":
        "finish-args-redundant-home-and-host"

    "warnings":
        "finish-args-contains-both-x11-and-wayland"
```

If you think problems listed above are a false positive, please report it here: https://github.com/flathub/flatpak-builder-lint

**Comment by Etaash-mathamsetty** [comment]
bump, could this get merged now? It's been officially announced for a while now

**Comment by tim77** [comment]
TBH i still didn't find enough time to test it properly, but basic test OK. RetroArch works with this new runtime.

**Pull request merged**
