### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by HugLifeTiZ**
Built fine for me, ran a couple of games just fine with it.

### CODE REVIEW

**Comment by RobLoach** [comment]
bot, build

**Comment by RobLoach** [comment]
@HugLifeTiZ Thanks! Didn't know the new runtime was out.

**Comment by j8r** [comment]
Any news?

**Comment by RobLoach** [comment]
@j8r Thanks for the ping! Build successfully, so going to merge this one :+1:

**Pull request merged**
