### PR TITLE
Update filesystem to "host", allowing access outside of home

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by dbenoy** [comment]
I suggest setting the default save and savestate directory to ~/.var/app/org.libretro.RetroArch/save and then using host:ro instead.

**Comment by dese11** [comment]
In a common linux install usually you expect people to have a data partition besides their home, it is my case, so I'd like to see this minor issue solved by default.

**Comment by Barthalion** [comment]
I don't think it's a good idea to grant filesystem access by default. You can do that on your own with `flatpak override` and probably via GNOME Software in the future.

**Comment by RobLoach** [comment]
Agreed! Let's find a better way around this, in a new PR.

**Pull request closed without merging**
