### PR TITLE
Add espeak

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by RobLoach** [comment]
While this makes espeak available, it doesn't use the correct audio device.

**Comment by orowith2os** [comment]
Is that an issue specific to the Flatpak? How does it find which audio device to use?

**Comment by RobLoach** [comment]
Perhaps we should just merge it? I have never used espeak, so I don't know how to make it use the same audio device as RetroArch.

**Comment by orowith2os** [comment]
I'd imagine it would use the default system audio device - but so long as it can somewhat work, that would be nice. The kinks can be worked out when people actually encounter them and provide more details.

**Comment by RobLoach** [comment]
@orowith2os Feel free to try this build out. If you manage to get it speaking, let me know. It's not working on my machine.

**Comment by RobLoach** [comment]
A second attempt https://github.com/flathub/org.libretro.RetroArch/pull/294

**Pull request closed without merging**
