### PR TITLE
Update libretro-database to fix file name length

### LINKED ISSUE #300: "File name too long" error when installing
`flatpak install` fails with a "File name too long" error:
```
$ flatpak install --user -y flathub org.libretro.RetroArch
Looking for matches…

org.libretro.RetroArch permissions:
    ipc       network       fallback-x11       pulseaudio            wayland
    x11       devices       multiarch          file access [1]       dbus access [2]

    [1] /run/udev:ro, host, xdg-config/kdeglobals:ro, xdg-run/app/com.discordapp.Discord:create,
        xdg-run/gamescope-0:ro
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.PowerManagement.Inhibit,
        org.freedesktop.ScreenSaver, org.freedesktop.login1, org.kde.KGlobalSettings,
        org.kde.kconfig.notify


        ID                             Branch         Op         Remote         Download
 1. [✗] org.libretro.RetroArch         stable         i          flathub        1.0 kB / 636.7 MB

Error: While trying to checkout d48aaef300f3c6ad3f1df9d40a79cda852c262a9ee631c7f902e3f52215996d8 into /home/andornaut/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/.d48aaef300f3c6ad3f1df9d40a79cda852c262a9ee631c7f902e3f52215996d8-nEeW6R: Hardlinking f4/3a21dedc3bb7fa376b6719e29fa267aec2327467e929668730ca228debf625.file to Ace Attorney Investigations - Miles Edgeworth (Europe) (Ace Attorney Investigations - Miles Edgeworth - Italian Translation (20151219) (AAIMEITA)).cht: File name too long
error: Failed to install org.libretro.RetroArch: While trying to checkout d48aaef300f3c6ad3f1df9d40a79cda852c262a9ee631c7f902e3f52215996d8 into /home/andornaut/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/.d48aaef300f3c6ad3f1df9d40a79cda852c262a9ee631c7f902e3f52215996d8-nEeW6R: Hardlinking f4/3a21dedc3bb7fa376b6719e29fa267aec2327467e929668730ca228debf625.file to Ace Attorney Investigations - Miles Edgeworth (Europe) (Ace Attorney Investigations - Miles Edgeworth - Italian Translation (20151219) (AAIMEITA)).cht: File name too long
```

Not sure if this is something that can be fixed in the flatpak or is my host environment. My `$HOME` dir is an ecryptfs filesystem overlaid on ext4.

### PR DESCRIPTION
**Pull request by RobLoach**
Fixes #300

### CODE REVIEW

**Comment by andornaut** [comment]
@RobLoach I'm still getting the "File name too long" error with the test build:
```
$ flatpak install --user https://dl.flathub.org/build-repo/126623/org.libretro.RetroArch.flatpakref

org.libretro.RetroArch permissions:
    ipc             network               fallback-x11          pulseaudio      wayland      x11      devices
    multiarch       file access [1]       dbus access [2]

    [1] /run/udev:ro, host, xdg-config/kdeglobals:ro, xdg-run/app/com.discordapp.Discord:create, xdg-run/gamescope-0:ro
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.PowerManagement.Inhibit, org.freedesktop.ScreenSaver, org.freedesktop.login1,
        org.kde.KGlobalSettings, org.kde.kconfig.notify


        ID                               Branch           Op           Remote                     Download
 1. [✗] org.libretro.RetroArch           test             i            retroarch-origin           299.3 MB / 636.7 MB

Error: While trying to checkout b5d1aafc654926726050773f666740ea771c23c7e83de6efc58b511e5a8049bb into /home/andornaut/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/test/.b5d1aafc654926726050773f666740ea771c23c7e83de6efc58b511e5a8049bb-XJj5uB: Hardlinking 58/41d31739705872349a60b6ac22fdb35b5f16bde8bfcc17b724f53968f365eb.file to Castlevania - Portrait of Ruin (USA) (Castlevania - Portrait of Ruin - Progenitors (v2.4.0) (Normal Nest of Evil - Reincarnated Soul Theme)).cht: File name too long
error: Failed to install org.libretro.RetroArch: While trying to checkout b5d1aafc654926726050773f666740ea771c23c7e83de6efc58b511e5a8049bb into /home/andornaut/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/test/.b5d1aafc654926726050773f666740ea771c23c7e83de6efc58b511e5a8049bb-XJj5uB: Hardlinking 58/41d31739705872349a60b6ac22fdb35b5f16bde8bfcc17b724f53968f365eb.file to Castlevania - Portrait of Ruin (USA) (Castlevania - Portrait of Ruin - Progenitors (v2.4.0) (Normal Nest of Evil - Reincarnated Soul Theme)).cht: File name too long
```

This time with `Castlevania - Portrait of Ruin (USA) (Castlevania - Portrait of Ruin - Progenitors (v2.4.0) (Normal Nest of Evil - Reincarnated Soul Theme)).cht`

**Comment by RobLoach** [comment]
Perhaps the limit on that file system is quite shorter than expected? Here are the files that are >127 characters long...

```
find -exec basename '{}' ';' | egrep '^.{127,}$'
Pokemon - Version Argent SoulSilver (France) (Pokemon - MindCrystal Version - English Translation (v3.0.2 Patch v6) (rodygo)).cht
Puyo Puyo! - Puyopuyo 15th Anniversary (Japan) (Rev 1) (Puyo Puyo! - Puyopuyo 15th Anniversary - English Translation (v1.2) (Hernan)).cht
Castlevania - Portrait of Ruin (USA) (Castlevania - Portrait of Ruin - Progenitors (v2.4.0) (Normal Nest of Evil - Reincarnated Soul Theme)).cht
Welcome to Animal Crossing - Wild World (USA) (Rev 1) (Welcome to Animal Crossing - Wild World - Singleplayer Nookington's (v1.1.1)).cht
Pokemon - SoulSilver Version (Europe) (Rev 10) (Pokemon - SoulSilver Version - Golden Edition (20210502) (Original Level Curve)).cht
Pokemon Mystery Dungeon - Explorers of Time + Pokemon Mystery Dungeon - Explorers of Darkness - Video (USA) (Demo) (DS Download Station).cht
Ni no Kuni - Shikkoku no Madoushi (Japan) (Ni no Kuni - Shikkoku no Madoushi - Russian Translation (v5.2b) (Dmitry Ivanov)).cht
Welcome to Animal Crossing - Wild World (Europe) (Welcome to Animal Crossing - Wild World - Singleplayer Nookington's (v1.1.1)).cht
Kanshuu Nihon Joushiki Ryoku Kentei Kyoukai - Imasara Hito ni wa Kikenai - Otona no Joushiki Ryoku Training DS (Japan) (Rev 1).cht
Pocket Monsters - Diamond (Japan) (Beta) (20060807) (Ganix) (Pocket Monsters - Diamond - English Translation (v1.0) (Unknown)).cht
Dragon Quest IV - Michibikareshi Mono-tachi (Japan) (Dragon Quest IV - Michibikareshi Mono-tachi - English Translation (v1.0.0) (concreted)).cht
Touhoku Daigaku Mirai Kagaku Gijutsu Kyoudou Kenkyuu Center - Kawashima Ryuuta Kyouju Kanshuu - Motto Nou o Kitaeru Otona no DS Training (Japan).cht
Legend of Zelda, The - Phantom Hourglass (USA) (Legend of Zelda, The - Phantom Hourglass - Russian Translation (v1.2) (Anton)).cht
Pokemon Mystery Dungeon - Explorers of Sky (USA) (Pokemon Mystery Dungeon - Explorers of Sky - Russian Translation (v1.0) (Pojirianets)).cht
Suzumiya Haruhi no Chokuretsu (Japan) (Suzumiya Haruhi no Chokuretsu - English Translation (v0.2) (Haroohie Translation Club)).cht
Okaeri! Chibi-Robo! - Happy Rich Oosouji! (Japan) (Okaeri! Chibi-Robo! - Happy Rich Oosouji! - English Translation (v1.1) (cjuub)).cht
Pokemon - White Version 2 (USA, Europe) (Pokemon - Volt White Version 2 - Redux (v1.4.0) (Complete Classic) (Original EVless)).cht
Welcome to Animal Crossing - Wild World (USA) (Welcome to Animal Crossing - Wild World - Singleplayer Nookington's (v1.1.1)).cht
Rockman EXE - Operate Shooting Star (Japan) (Rockman EXE - Operate Shooting Star - English Translation (v1.0) (Greiga Master)).cht
Nine Hours, Nine Persons, Nine Doors (USA) (Nine Hours, Nine Persons, Nine Doors - Italian Translation (v1.3) (All-Ice Team)).cht
Irozuki Tingle no Koi no Balloon Trip (Japan) (Irozuki Tingle no Koi no Balloon Trip - English Translation (v1.1) (Team Tingle)).cht
Legend of Zelda, The - Spirit Tracks (USA) (Legend of Zelda, The - Spirit Tracks - Russian Translation (v1.1) (apollo90, kvark)).cht
Dragon Quest IV - Michibikareshi Mono-tachi (Japan) (Dragon Quest IV - Michibikareshi Mono-tachi - English Translation (v1.0) (spiderfreak1011)).cht
Pokemon - HeartGold Version (Europe) (Rev 10) (Pokemon - HeartGold Version - Golden Edition (20210502) (Original Level Curve)).cht
Pokemon - Black Version 2 (USA, Europe) (Pokemon - Blaze Black Version 2 - Redux (v1.4.0) (Complete Classic) (Original EVless)).cht
Touhoku Daigaku Mirai Kagaku Gijutsu Kyoudou Kenkyuu Center - Kawashima Ryuuta Kyouju Kanshuu - Nou o Kitaeru Otona no DS Training (Japan).cht
Puyo Puyo!! - Puyopuyo 20th Anniversary (Japan) (Puyo Puyo!! - Puyopuyo 20th Anniversary - English Translation (v1.2) (Precise Museum)).cht
Kochira Katsushika Ku Kameari Kouen Mae Hashutsujo - Kateba Tengoku! Makereba Jigoku! - Ryoutsu-ryuu Ikkakusenkin Daisakusen! (Japan).cht
Soul Eater - Medusa no Inbou (Japan) (Soul Eater - Medusa no Inbou - English Translation (v1.2) (Anime Game Translations Team)).cht
Tales of Hearts - Anime Movie Edition (Japan) (Tales of Hearts - Anime Movie Edition - English Translation (v1.0) (Kajitani-Eizan)).cht
Maritrini, Freelance Monster Slayer en - Las Increibles Vicisitudes de Despertarse Resacosa con Fred (2012)(Mojon Twins, The).cht
```

**Comment by andornaut** [comment]
@RobLoach I believe the limit is 143 characters. I've created [an issue](https://github.com/libretro/libretro-database/issues/1483) on the libretro-database project with more details.

I think only 4 more files need to be renamed.

> Would you be able to go through and shorten the file names?

Sure, though I'm not sure what parts of the names can be renamed without affecting/breaking anything else?

**Comment by andornaut** [comment]
@RobLoach I've opened [a PR on libretro-database](https://github.com/libretro/libretro-database/pull/1484)

**Pull request merged**
